name: hacko-backend-go production deployment

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Docker image
      run: |
        docker build -t myusername/my-backend:latest .
    - name: Push Docker image
      run: |
        docker push myusername/my-backend:latest
    
  deploy:
    runs-on: ubuntu-latest
    needs: build  
    
    steps:
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }} 

    - name: Pull Docker image and run Docker Compose on VPS
      run: |
        ssh -o StrictHostKeyChecking=no user@vps-ip "cd /opt/my-project && docker-compose pull && docker-compose up -d"
