name: hacko-backend-go production deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
  
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
  
    - name: Build and Push Docker image with cache
      env:
        DOCKER_BUILDKIT: 1
      run: |
        docker pull mortomulu/hacko:latest || true
        docker buildx build \
          --platform linux/amd64 \
          --cache-from=mortomulu/hacko:latest \
          --cache-to=type=inline \
          -t mortomulu/hacko:latest \
          --push .
          
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Pull Docker image and restart container
      run: |
        ssh -o StrictHostKeyChecking=no root@206.189.88.38 <<EOF
            cd /hacko
            echo "Pulling latest image..."
            docker pull mortomulu/hacko:latest || { echo "Failed to pull image"; exit 1; }
            echo "Stopping and removing old container..."
            docker stop hacko_container || true
            docker rm hacko_container || true
            echo "Starting new container..."
            docker run -d -p 3000:3000 -v .env:/app/.env --name hacko_container mortomulu/hacko:latest
            echo "Pruning unused images..."
            docker image prune -f
        EOF
